[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200

build_flags =
    -I include
    -I .pio/libdeps/teensy41/FreeRTOS-Kernel/include
    -I .pio/libdeps/teensy41/FreeRTOS-Kernel/portable/GCC/ARM_CM7/r0p1
    -D portUSE_MPU_WRAPPERS=0
    -D configTICK_TYPE_WIDTH_IN_BITS=TICK_TYPE_WIDTH_32_BITS

build_src_filter =
    +<*>
    +<../.pio/libdeps/teensy41/FreeRTOS-Kernel/list.c>
    +<../.pio/libdeps/teensy41/FreeRTOS-Kernel/queue.c>
    +<../.pio/libdeps/teensy41/FreeRTOS-Kernel/tasks.c>
    +<../.pio/libdeps/teensy41/FreeRTOS-Kernel/timers.c>
    +<../.pio/libdeps/teensy41/FreeRTOS-Kernel/event_groups.c>
    +<../.pio/libdeps/teensy41/FreeRTOS-Kernel/stream_buffer.c>
    +<../.pio/libdeps/teensy41/FreeRTOS-Kernel/croutine.c>
    +<../.pio/libdeps/teensy41/FreeRTOS-Kernel/portable/MemMang/heap_4.c>
    +<../.pio/libdeps/teensy41/FreeRTOS-Kernel/portable/GCC/ARM_CM7/r0p1/port.c>

lib_deps =
    https://github.com/FreeRTOS/FreeRTOS-Kernel.git
    https://github.com/mavlink/c_library_v2.git#master
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306

lib_ignore =
    FreeRTOS-Kernel
